version: "3.9"
services:
  application: 
    build: .
    ports:
      - 8080:80
    networks:
      - network
  database:
    image: "postgres"
    env_file:
      - ../.env 
    networks:
      - network
networks:
  network:
    driver: bridge