version: "3.9"
services:
  application: 
    build: .
    ports:
      - 8080:80
    networks:
      - network
    volumes:
      - app:/app/wwwroot
    env_file:
      - .env.application
  database:
    image: "postgres"
    env_file:
      - .env.db 
    networks:
      - network
    volumes:
      - database:/var/lib/postgresql/data
networks:
  network:
    driver: bridge
volumes:
  app:
  database:

