version: "3.9"
services:
  application: 
    build: .
    ports:
      - 8080:80
    networks:
      - network
    volumes:
      - app:/app/wwwroot
  database:
    image: "postgres"
    env_file:
      - .env 
    networks:
      - network
    volumes:
      - ${LOCAL_DB_PATH}:/var/lib/postgresql/data
networks:
  network:
    driver: bridge
volumes:
  app:

