name: 01-docker-build-on-PR

on:
  workflow_dispatch:
  push:
    branches: [ "homework/*" ]
    paths:
      - "academy_project/app/src/**"
      - "academy_project/app/Dockerfile"
  pull_request:
    branches: [ "main" ]
    paths:
      - "academy_project/app/src/**"
      - "academy_project/app/Dockerfile"

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout 
        uses: actions/checkout@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ./academy_project/app
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/devops-academy:latest
      - 
        name: Report status
        if: always()
        uses: ravsamhq/notify-slack-action@v2
        with:
          status: ${{ job.status }}
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_ULR }}