name: 02-docker-build-on-merge-to-main

on:
  workflow_dispatch:
  pull_request:
    types:
      - closed
    paths:
      - "academy_project/app/src/**"
      - "academy_project/app/Dockerfile"

jobs:

  build:
    #if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout 
        uses: actions/checkout@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ./academy_project/app
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/devops-academy:latest
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Report status
        if: always()
        uses: ravsamhq/notify-slack-action@v2
        with:
          status: ${{ job.status }}
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_ULR }}
